# Generated by Django 3.1.7 on 2021-06-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_issuer',
            field=models.BooleanField(default=False),
        ),
    ]
