# Generated by Django 3.1.7 on 2021-06-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='anydesk_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
