# Generated by Django 3.1.7 on 2021-06-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_user_is_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_agent',
            new_name='is_technician',
        ),
    ]
