# Generated by Django 3.1.7 on 2021-06-13 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20210612_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues.technician'),
        ),
    ]
