# Generated by Django 3.1.7 on 2021-06-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20210613_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
