# Generated by Django 3.1.7 on 2021-06-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_issuer',
            field=models.BooleanField(default=True),
        ),
    ]
